# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'de.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 892)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_process = QtWidgets.QLabel(self.centralwidget)
        self.label_process.setGeometry(QtCore.QRect(150, 780, 411, 51))
        self.label_process.setText("")
        self.label_process.setObjectName("label_process")
        self.label_txet = QtWidgets.QLabel(self.centralwidget)
        self.label_txet.setGeometry(QtCore.QRect(20, 780, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_txet.setFont(font)
        self.label_txet.setTextFormat(QtCore.Qt.AutoText)
        self.label_txet.setObjectName("label_txet")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 21, 653, 741))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.open_button = QtWidgets.QPushButton(self.widget)
        self.open_button.setMinimumSize(QtCore.QSize(161, 61))
        self.open_button.setObjectName("open_button")
        self.gridLayout.addWidget(self.open_button, 0, 0, 1, 1)
        self.start_button = QtWidgets.QPushButton(self.widget)
        self.start_button.setMinimumSize(QtCore.QSize(161, 61))
        self.start_button.setObjectName("start_button")
        self.gridLayout.addWidget(self.start_button, 0, 1, 1, 1)
        self.label_show = QtWidgets.QLabel(self.widget)
        self.label_show.setMinimumSize(QtCore.QSize(651, 671))
        self.label_show.setText("")
        self.label_show.setObjectName("label_show")
        self.gridLayout.addWidget(self.label_show, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_txet.setText(_translate("MainWindow", "运行信息："))
        self.open_button.setText(_translate("MainWindow", "打开视频"))
        self.start_button.setText(_translate("MainWindow", "测试"))
